package com.seobuk.chess.learn

data class BoardArrowSpec(val from: String, val to: String) // square names, e.g. "f3", "e5"

data class StrategyTopic(
    val id: String,
    val category: String,
    val title: String,
    val emoji: String,
    val summary: String,
    val points: List<String>,
    val exampleFen: String?,
    val exampleCaption: String?,
    val highlights: List<String> = emptyList(),
    val arrows: List<BoardArrowSpec> = emptyList(),
    val minLevel: Int = 1, // AI level (1..10) where this topic starts to matter most
)

object StrategyGuide {
    const val OPENING = "오프닝 원칙"
    const val TACTICS = "전술"
    const val MIDDLEGAME = "중반 전략"
    const val ENDGAME = "엔드게임"

    val categories: List<String> = listOf(OPENING, TACTICS, MIDDLEGAME, ENDGAME)

    val topics: List<StrategyTopic> = listOf(
        // ───────────── 오프닝 원칙 ─────────────
        StrategyTopic(
            id = "center",
            category = OPENING,
            title = "중앙 장악",
            emoji = "🎯",
            summary = "체스판의 중앙(d4, d5, e4, e5)은 모든 기물이 가장 힘을 내는 곳이에요. 중앙을 차지한 쪽이 공간과 주도권을 얻어요.",
            points = listOf(
                "첫 수는 e4나 d4처럼 중앙 폰으로 시작해요.",
                "중앙의 나이트는 8칸을 공격하지만, 구석의 나이트는 2칸밖에 못 봐요.",
                "중앙 폰은 상대 기물이 좋은 칸에 오지 못하게 막아 줘요.",
                "직접 차지하지 않아도 기물로 중앙을 '노리는' 것도 중앙 장악이에요.",
            ),
            exampleFen = "rnbqkbnr/ppp2ppp/3p4/4p3/3PP3/5N2/PPP2PPP/RNBQKB1R b KQkq - 0 3",
            exampleCaption = "백의 e4·d4 폰이 중앙을 차지했어요. d4 폰과 f3 나이트가 e5를 함께 노려요.",
            highlights = listOf("d4", "e4", "d5", "e5"),
            arrows = arrows("d4" to "e5", "f3" to "e5"),
            minLevel = 1,
        ),
        StrategyTopic(
            id = "development",
            category = OPENING,
            title = "빠른 기물 전개",
            emoji = "🚀",
            summary = "오프닝에서는 나이트와 비숍을 빨리 꺼내 싸움에 참여시키는 것이 중요해요. 폰이나 한 기물만 여러 번 움직이면 전개가 늦어져요.",
            points = listOf(
                "나이트와 비숍을 먼저, 룩과 퀸은 나중에 꺼내요.",
                "특별한 이유가 없다면 같은 기물을 두 번 움직이지 않아요.",
                "퀸을 너무 일찍 꺼내면 상대 기물에게 쫓기며 시간을 잃어요.",
                "폰은 중앙 폰 한두 개만 움직이고 나머지는 기물 전개에 집중해요.",
            ),
            exampleFen = "rnbqkbnr/1pp2ppp/p2p4/4p3/2B1P3/2N2N2/PPPP1PPP/R1BQK2R b KQkq - 1 4",
            exampleCaption = "백은 나이트 두 개와 비숍을 꺼냈지만, 흑은 폰만 세 번 움직였어요. 전개가 앞선 백이 훨씬 편해요.",
            highlights = listOf("c3", "f3", "c4"),
            arrows = arrows("c4" to "f7"),
            minLevel = 1,
        ),
        StrategyTopic(
            id = "castling",
            category = OPENING,
            title = "캐슬링과 킹 안전",
            emoji = "🏰",
            summary = "킹이 중앙에 오래 머물면 열린 파일에서 공격받기 쉬워요. 보통 10수 안에 캐슬링해서 킹을 안전한 구석으로 옮기고 룩을 싸움에 참여시켜요.",
            points = listOf(
                "캐슬링은 킹을 안전하게 하고 룩을 중앙 쪽으로 꺼내는 일석이조의 수예요.",
                "킹과 룩 사이가 비어 있고, 둘 다 한 번도 움직이지 않았어야 캐슬링할 수 있어요.",
                "체크를 받고 있거나 킹이 지나가는 칸이 공격받으면 캐슬링할 수 없어요.",
                "캐슬링한 뒤에는 킹 앞 폰(f, g, h)을 함부로 밀지 않아요.",
            ),
            exampleFen = "r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/3P1N2/PPP2PPP/RNBQK2R w KQkq - 1 5",
            exampleCaption = "킹은 e1에서 g1로 두 칸, 룩은 h1에서 f1로 옮겨요. 한 수에 킹은 폰 방패 뒤로 숨고 룩은 싸움에 가까워져요.",
            highlights = listOf("f2", "g2", "h2"),
            arrows = arrows("e1" to "g1", "h1" to "f1"),
            minLevel = 1,
        ),
        StrategyTopic(
            id = "piece_value",
            category = OPENING,
            title = "기물의 가치",
            emoji = "⚖️",
            summary = "기물마다 대략적인 점수가 있어요. 교환할 때 점수를 비교하면 손해 보는 거래를 피할 수 있어요.",
            points = listOf(
                "폰 1점, 나이트 3점, 비숍 3점, 룩 5점, 퀸 9점이에요. 킹은 값을 매길 수 없어요.",
                "룩을 나이트나 비숍과 바꾸면 약 2점 손해('익스체인지'를 잃었다고 해요)예요.",
                "잡기 전에 '상대가 다시 잡을 수 있나?'를 꼭 확인해요.",
                "점수는 기준일 뿐이에요. 활발하게 움직이는 기물은 점수보다 더 큰 힘을 내요.",
            ),
            exampleFen = "4r1k1/pp3ppp/2p5/3n4/8/5N2/PPP2PPP/3R2K1 w - - 0 1",
            exampleCaption = "Rxd5?는 나이트(3점)를 얻지만 c6 폰이 다시 잡아 룩(5점)을 잃어요. 결국 2점 손해예요.",
            highlights = listOf("d5", "c6"),
            arrows = arrows("d1" to "d5", "c6" to "d5"),
            minLevel = 1,
        ),

        // ───────────── 전술 ─────────────
        StrategyTopic(
            id = "blunder_check",
            category = TACTICS,
            title = "수 두기 전 안전 점검",
            emoji = "🔍",
            summary = "실력이 가장 빨리 느는 습관이에요. 수를 두기 전에 상대의 마지막 수가 무엇을 노리는지, 내 기물이 안전한지 먼저 확인해요.",
            points = listOf(
                "상대가 방금 둔 수의 목적(위협)부터 찾아요.",
                "체크 → 잡기 → 위협 순서로 양쪽의 강한 수를 살펴봐요.",
                "지켜 주는 기물이 없는 '공짜 기물'이 없는지 확인해요.",
                "좋은 수가 보여도 더 좋은 수가 있는지 한 번 더 찾아봐요.",
            ),
            exampleFen = "r1bqkbnr/pppp1ppp/2n5/4p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR b KQkq - 3 3",
            exampleCaption = "흑 차례예요. 백이 Qxf7#을 노리고 있어요. 위협을 먼저 보면 ...g6나 ...Qe7로 쉽게 막을 수 있어요.",
            highlights = listOf("f7"),
            arrows = arrows("h5" to "f7", "c4" to "f7"),
            minLevel = 1,
        ),
        StrategyTopic(
            id = "fork",
            category = TACTICS,
            title = "포크 (양수겸장)",
            emoji = "🍴",
            summary = "한 기물이 동시에 두 개 이상의 목표를 공격하는 전술이에요. 상대는 하나밖에 지킬 수 없어서 나머지를 잃어요. 특히 나이트 포크가 무서워요.",
            points = listOf(
                "킹, 퀸, 룩처럼 값비싼 기물 두 개를 한꺼번에 노려요.",
                "체크와 함께하는 포크는 상대가 피할 방법이 거의 없어요.",
                "나이트는 움직임이 특이해서 상대가 포크를 잘 못 봐요.",
                "폰 하나로 기물 두 개를 공격하는 폰 포크도 강력해요.",
            ),
            exampleFen = "r3k3/pp3ppp/8/3N4/8/8/PPP2PPP/4K3 w - - 0 1",
            exampleCaption = "Nc7+! 나이트가 킹과 a8 룩을 동시에 공격해요. 킹이 피하고 나면 룩을 잡아요.",
            highlights = listOf("e8", "a8", "c7"),
            arrows = arrows("d5" to "c7", "c7" to "e8", "c7" to "a8"),
            minLevel = 2,
        ),
        StrategyTopic(
            id = "pin",
            category = TACTICS,
            title = "핀",
            emoji = "📌",
            summary = "공격받은 기물이 움직이면 뒤에 있는 더 중요한 기물이 잡히는 상황이에요. 킹 앞의 핀은 아예 움직일 수 없는 '절대 핀'이에요.",
            points = listOf(
                "비숍, 룩, 퀸처럼 멀리 가는 기물만 핀을 걸 수 있어요.",
                "핀 당한 기물은 폰 같은 값싼 기물로 한 번 더 공격하면 좋아요.",
                "킹 앞 핀은 절대 핀, 퀸 앞 핀은 움직일 수는 있지만 퀸을 잃는 상대 핀이에요.",
                "핀에 걸렸다면 킹을 옮기거나 사이를 막아 풀어요.",
            ),
            exampleFen = "4k3/pp3ppp/2n5/1B6/3P4/8/PP3PPP/6K1 w - - 0 1",
            exampleCaption = "b5 비숍이 c6 나이트를 킹에게 핀했어요. d5!로 폰까지 공격하면 나이트는 도망칠 수 없어요.",
            highlights = listOf("c6", "e8"),
            arrows = arrows("b5" to "e8", "d4" to "d5"),
            minLevel = 3,
        ),
        StrategyTopic(
            id = "skewer",
            category = TACTICS,
            title = "스큐어 (꼬치 공격)",
            emoji = "🍢",
            summary = "핀과 반대예요. 앞에 있는 비싼 기물을 공격해 비키게 만든 뒤, 뒤에 있는 기물을 잡는 전술이에요.",
            points = listOf(
                "킹이나 퀸처럼 비싼 기물이 앞에 있을 때 효과적이에요.",
                "체크로 시작하는 스큐어는 상대가 무조건 킹을 비켜야 해요.",
                "킹과 퀸이 같은 줄(파일, 랭크, 대각선)에 서 있으면 위험 신호예요.",
            ),
            exampleFen = "8/5p1p/2k4q/8/8/8/5PPP/R5K1 w - - 0 1",
            exampleCaption = "Ra6+! 킹이 체크를 피해 비키면, 같은 줄 뒤에 있던 h6 퀸을 잡을 수 있어요.",
            highlights = listOf("c6", "h6"),
            arrows = arrows("a1" to "a6", "a6" to "h6"),
            minLevel = 3,
        ),
        StrategyTopic(
            id = "discovered_attack",
            category = TACTICS,
            title = "디스커버드 어택",
            emoji = "💥",
            summary = "앞을 막고 있던 기물이 비키면서 뒤에 숨어 있던 기물의 공격이 드러나는 전술이에요. 비키는 기물까지 공격하면 한 번에 두 곳을 노릴 수 있어요.",
            points = listOf(
                "내 룩, 비숍, 퀸 앞에 내 기물이 서 있다면 디스커버드 어택 기회를 찾아봐요.",
                "드러난 공격이 체크라면 '디스커버드 체크'로 더 강력해져요.",
                "두 기물이 동시에 체크하는 '더블 체크'는 킹이 움직이는 수밖에 없어요.",
            ),
            exampleFen = "3qk2r/ppp2ppp/8/3PN3/8/8/5PPP/4R1K1 w - - 0 1",
            exampleCaption = "Nc6+! 나이트가 비키자 e1 룩이 킹을 체크하고, 동시에 나이트가 d8 퀸을 공격해요.",
            highlights = listOf("e8", "d8"),
            arrows = arrows("e5" to "c6", "e1" to "e8", "c6" to "d8"),
            minLevel = 4,
        ),
        StrategyTopic(
            id = "back_rank",
            category = TACTICS,
            title = "백랭크 메이트",
            emoji = "🚪",
            summary = "캐슬링한 킹 앞의 폰 세 개가 오히려 탈출구를 막아서, 마지막 줄(백랭크)에서 룩이나 퀸에게 체크메이트 당하는 패턴이에요.",
            points = listOf(
                "킹 앞의 f, g, h 폰이 모두 제자리면 백랭크가 약해요.",
                "여유가 있을 때 h3(흑은 ...h6) 같은 '숨구멍'을 만들어 두면 안전해요.",
                "백랭크를 지키는 기물이 하나뿐이면 그 기물을 끌어내는 전술을 조심해요.",
                "상대 백랭크가 약하면 룩을 열린 파일로 보내 노려요.",
            ),
            exampleFen = "6k1/pp3ppp/8/8/8/8/PP3PPP/3R2K1 w - - 0 1",
            exampleCaption = "Rd8#! 흑 킹은 자기 폰(f7, g7, h7)에 막혀 도망칠 곳이 없어요.",
            highlights = listOf("f7", "g7", "h7", "d8"),
            arrows = arrows("d1" to "d8"),
            minLevel = 3,
        ),
        StrategyTopic(
            id = "overloading",
            category = TACTICS,
            title = "오버로딩과 디플렉션",
            emoji = "🏋️",
            summary = "한 기물이 두 가지 임무를 동시에 맡고 있으면 '과부하(오버로딩)' 상태예요. 한쪽 임무를 건드려 그 기물을 끌어내면(디플렉션) 다른 쪽이 무너져요.",
            points = listOf(
                "상대 기물 하나가 무엇을 지키고 있는지 모두 세어 봐요.",
                "두 곳을 지키는 기물이 보이면 한쪽을 공격해 끌어내요.",
                "내 기물을 희생해서 수비수를 끌어내는 경우가 많아요.",
            ),
            exampleFen = "3r2k1/pp3ppp/8/3q4/8/8/PP1Q1PPP/4R1K1 w - - 0 1",
            exampleCaption = "d8 룩은 d5 퀸과 백랭크(e8)를 혼자 지켜요. Qxd5! ...Rxd5 후 Re8#로 끝나요.",
            highlights = listOf("d8", "e8"),
            arrows = arrows("d2" to "d5", "e1" to "e8"),
            minLevel = 6,
        ),

        // ───────────── 중반 전략 ─────────────
        StrategyTopic(
            id = "open_file",
            category = MIDDLEGAME,
            title = "오픈 파일과 룩",
            emoji = "🛣️",
            summary = "폰이 하나도 없는 세로줄(파일)을 오픈 파일이라고 해요. 룩은 오픈 파일에서 가장 강해지고, 7랭크까지 침투하면 상대 폰을 쓸어 담아요.",
            points = listOf(
                "룩은 폰이 없는 열린 파일에 놓아요.",
                "룩 두 개를 같은 파일에 겹치면(더블링) 힘이 두 배가 돼요.",
                "상대 진영 7랭크(흑이라면 2랭크)에 들어간 룩은 폰을 잡고 킹을 가둬요.",
                "상대가 먼저 오픈 파일을 차지하면 내 룩으로 맞서 교환을 제안해요.",
            ),
            exampleFen = "r4rk1/pp3ppp/2p5/8/8/8/PPPR1PPP/3R2K1 w - - 0 1",
            exampleCaption = "d파일에는 폰이 하나도 없어요. 룩 두 개를 겹친 백이 Rd7으로 7랭크에 침투해요.",
            highlights = listOf("d7", "b7", "f7"),
            arrows = arrows("d2" to "d7"),
            minLevel = 5,
        ),
        StrategyTopic(
            id = "bishops",
            category = MIDDLEGAME,
            title = "비숍 페어와 좋은·나쁜 비숍",
            emoji = "🔦",
            summary = "비숍 두 개를 모두 가진 '비숍 페어'는 열린 판에서 큰 힘을 내요. 또 자기 폰이 비숍과 같은 색 칸에 몰려 있으면 비숍이 막혀 '나쁜 비숍'이 돼요.",
            points = listOf(
                "비숍 페어는 열린 포지션과 엔드게임에서 특히 강해요.",
                "폰을 비숍과 다른 색 칸에 두면 비숍이 자유로워져요.",
                "나쁜 비숍은 폰 사슬 밖으로 꺼내거나 교환해요.",
                "상대의 나쁜 비숍은 남겨 두고, 좋은 비숍과 교환하려고 해요.",
            ),
            exampleFen = "2b3k1/pp3ppp/4p3/3pP3/3P4/3B4/PP3PPP/6K1 w - - 0 1",
            exampleCaption = "흑 비숍(c8)은 자기 폰(d5·e6)에 갇힌 나쁜 비숍, 백 비숍(d3)은 h7까지 시원하게 뻗은 좋은 비숍이에요.",
            highlights = listOf("c8", "d5", "e6"),
            arrows = arrows("d3" to "h7"),
            minLevel = 7,
        ),
        StrategyTopic(
            id = "pawn_structure",
            category = MIDDLEGAME,
            title = "폰 구조: 고립, 더블, 패스드 폰",
            emoji = "⛓️",
            summary = "폰은 뒤로 물러날 수 없어서 한 번 생긴 약점이 오래가요. 폰 구조의 약점과 장점을 알면 중반 계획이 쉬워져요.",
            points = listOf(
                "고립 폰: 옆 파일에 같은 편 폰이 없어서 기물로만 지켜야 하는 약점이에요.",
                "더블 폰: 같은 파일에 두 개가 겹쳐 서로 돕지 못해요.",
                "패스드 폰: 앞을 막거나 옆에서 잡을 상대 폰이 없어 퀸이 될 수 있는 강력한 폰이에요.",
                "내 패스드 폰은 밀고, 상대 패스드 폰은 바로 앞 칸을 막아요.",
            ),
            exampleFen = "3r2k1/5p1p/5p2/3p4/P7/4P3/5PPP/3R2K1 w - - 0 1",
            exampleCaption = "a4는 막을 흑 폰이 없는 패스드 폰, d5는 고립 폰, f7·f6는 더블 폰이에요. 백은 a-폰을 밀고 d5를 노려요.",
            highlights = listOf("a4", "d5", "f6", "f7"),
            arrows = arrows("a4" to "a8", "d1" to "d5"),
            minLevel = 6,
        ),
        StrategyTopic(
            id = "outpost",
            category = MIDDLEGAME,
            title = "약한 칸과 아웃포스트",
            emoji = "🏕️",
            summary = "상대 폰이 더 이상 공격할 수 없는 칸을 '약한 칸(구멍)'이라고 해요. 그곳에 내 폰이 받쳐 주는 나이트를 세우면 쫓아낼 수 없는 거점(아웃포스트)이 돼요.",
            points = listOf(
                "폰이 앞으로 나가면 그 옆 칸들은 영원히 약해질 수 있어요.",
                "아웃포스트에는 나이트가 가장 잘 어울려요.",
                "내 폰으로 아웃포스트를 받쳐 주면 상대가 교환하기도 어려워요.",
                "상대가 좋은 칸을 노리면 기물 교환으로 미리 없애요.",
            ),
            exampleFen = "r3rbk1/pp3ppp/3p4/3Np3/4P3/8/PPP2PPP/3R1RK1 w - - 0 1",
            exampleCaption = "d5는 흑 폰이 공격할 수 없는 구멍이에요. e4 폰이 받쳐 주는 d5 나이트가 흑 진영 깊숙이 영향을 줘요.",
            highlights = listOf("d5"),
            arrows = arrows("e4" to "d5", "d5" to "c7", "d5" to "f6"),
            minLevel = 7,
        ),

        // ───────────── 엔드게임 ─────────────
        StrategyTopic(
            id = "king_activity",
            category = ENDGAME,
            title = "엔드게임 킹 활성화",
            emoji = "🤴",
            summary = "중반까지는 숨어 있어야 했던 킹이, 퀸이 사라진 엔드게임에서는 강력한 공격 기물이 돼요. 킹을 중앙으로 먼저 데려가는 쪽이 유리해요.",
            points = listOf(
                "퀸이 교환되면 킹을 중앙으로 걸어 나오게 해요.",
                "킹은 상대 폰을 막고, 내 폰이 퀸이 되도록 호위해요.",
                "폰 엔드게임에서는 킹의 한 수 차이가 승패를 가려요.",
            ),
            exampleFen = "6k1/pp3ppp/8/8/8/5P2/PP4PP/6K1 w - - 0 1",
            exampleCaption = "퀸이 없는 엔드게임이에요. 백 킹은 f2, e3를 거쳐 중앙 d4로 먼저 출발해요.",
            highlights = listOf("d4"),
            arrows = arrows("g1" to "f2", "f2" to "e3", "e3" to "d4"),
            minLevel = 4,
        ),
        StrategyTopic(
            id = "opposition",
            category = ENDGAME,
            title = "오포지션",
            emoji = "🆚",
            summary = "두 킹이 한 칸을 사이에 두고 마주 볼 때, 상대가 둘 차례라면 내가 '오포지션'을 가진 거예요. 킹과 폰 엔드게임의 승패를 가르는 핵심 개념이에요.",
            points = listOf(
                "킹끼리는 붙을 수 없어서, 마주 본 상태에서 둘 차례인 쪽이 길을 비켜 줘야 해요.",
                "폰 앞에 킹을 두고 오포지션을 잡으면 폰을 퀸으로 만들 수 있어요.",
                "킹이 폰보다 먼저 6랭크에 도착하면 거의 이겨요(가장자리 폰은 예외).",
                "막는 쪽은 폰 앞을 지키며 오포지션을 잡아 무승부를 노려요.",
            ),
            exampleFen = "8/4k3/8/4K3/4P3/8/8/8 b - - 0 1",
            exampleCaption = "흑 차례라서 백이 오포지션을 가졌어요. 흑 킹이 비키면 백 킹이 d6나 f6로 들어가 이겨요. 백 차례였다면 무승부예요.",
            highlights = listOf("e5", "e7"),
            arrows = arrows("e5" to "d6", "e5" to "f6"),
            minLevel = 5,
        ),
        StrategyTopic(
            id = "rook_endgame",
            category = ENDGAME,
            title = "룩 엔드게임: 루세나와 필리도르",
            emoji = "🌉",
            summary = "가장 자주 나오는 엔드게임이 룩 엔드게임이에요. 이기는 쪽은 '루세나(다리 놓기)', 막는 쪽은 '필리도르(3랭크 방어)'만 알아도 절반은 성공이에요.",
            points = listOf(
                "루세나: 폰이 7랭크에 있고 킹이 그 앞에 있으면, 룩을 4랭크로 올려 '다리'를 놓고 킹을 빼내요.",
                "필리도르: 막는 쪽은 룩으로 자기 진영 3번째 줄을 지켜 상대 킹이 못 들어오게 해요.",
                "상대 폰이 그 줄까지 올라오면 룩을 맨 뒤로 보내 뒤에서 계속 체크해요.",
                "룩은 패스드 폰의 뒤에 두는 것이 가장 좋아요.",
            ),
            exampleFen = "3K4/3P2k1/8/8/8/8/2r5/5R2 w - - 0 1",
            exampleCaption = "루세나 포지션: Rf4!로 다리를 준비하고 킹이 e7로 나와요. 흑 룩의 체크가 이어지면 룩을 d4로 옮겨 막아요.",
            highlights = listOf("d7", "f4", "d4"),
            arrows = arrows("f1" to "f4", "d8" to "e7"),
            minLevel = 8,
        ),
        StrategyTopic(
            id = "queen_mate",
            category = ENDGAME,
            title = "퀸+킹 기본 메이트",
            emoji = "👸",
            summary = "퀸과 킹만 남으면 반드시 이겨야 해요. 퀸으로 상대 킹이 움직일 공간을 점점 좁힌 뒤, 내 킹을 가까이 데려와 마무리해요.",
            points = listOf(
                "퀸을 상대 킹에게서 나이트 점프 거리에 두면 킹이 갇힌 상자가 점점 작아져요.",
                "상대 킹을 가장자리로 몰아요.",
                "마지막에는 내 킹을 데려와 퀸을 지켜 줘요.",
                "상대가 둘 곳이 없는데 체크도 아니면 스테일메이트(무승부)예요. 상대 킹의 빈칸을 항상 확인해요.",
            ),
            exampleFen = "7k/8/5K2/8/8/8/8/6Q1 w - - 0 1",
            exampleCaption = "Qg7#! 백 킹이 퀸을 지켜 줘요. 하지만 Qg6??는 흑이 둘 곳이 없는 스테일메이트(무승부)예요.",
            highlights = listOf("g7", "h8"),
            arrows = arrows("g1" to "g7"),
            minLevel = 2,
        ),
        StrategyTopic(
            id = "rook_mate",
            category = ENDGAME,
            title = "룩+킹 기본 메이트",
            emoji = "🏁",
            summary = "룩과 킹으로도 반드시 메이트할 수 있어요. 룩으로 상대 킹을 한 줄씩 밀어내고, 킹끼리 마주 보는 순간 룩으로 마지막 줄을 체크해요.",
            points = listOf(
                "룩으로 상대 킹을 한 줄씩 가장자리로 밀어내요.",
                "내 킹을 상대 킹 맞은편(오포지션)으로 데려와요.",
                "킹끼리 마주 볼 때 룩으로 마지막 줄을 체크하면 메이트예요.",
                "룩이 상대 킹에게 잡히지 않도록 멀리서 체크해요.",
            ),
            exampleFen = "6k1/8/6K1/8/8/8/8/R7 w - - 0 1",
            exampleCaption = "킹끼리 마주 본 순간 Ra8#! 룩은 8랭크를, 백 킹은 f7, g7, h7을 막아요.",
            highlights = listOf("g6", "g8"),
            arrows = arrows("a1" to "a8"),
            minLevel = 3,
        ),
    )

    fun byId(id: String): StrategyTopic? = topics.firstOrNull { it.id == id }
}

private fun arrows(vararg a: Pair<String, String>): List<BoardArrowSpec> =
    a.map { BoardArrowSpec(it.first, it.second) }
